"""add parent_id to items

Revision ID: 25ada616d58e
Revises: 806391e9a77b
Create Date: 2026-08-29 11:34:33.179852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ada616d58e'
down_revision: Union[str, Sequence[str], None] = '806391e9a77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_parent_id'), 'items', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'items', 'items', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_parent_id'), table_name='items')
    op.drop_column('items', 'parent_id')
    # ### end Alembic commands ###
