"""add is_important and is_archived to items

Revision ID: 25db53ed1323
Revises: c0beeac3cf4a
Create Date: 2026-08-08 12:42:09.813186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25db53ed1323'
down_revision: Union[str, Sequence[str], None] = 'c0beeac3cf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_important', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_archived')
    op.drop_column('items', 'is_important')
    # ### end Alembic commands ###
