"""add due_date to items

Revision ID: 3eca49b48b7a
Revises: 7d0cd9d1f61b
Create Date: 2026-07-25 08:01:07.663767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eca49b48b7a'
down_revision: Union[str, Sequence[str], None] = '7d0cd9d1f61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'due_date')
    # ### end Alembic commands ###
