"""add position to items

Revision ID: 767f6d868058
Revises: aab41d29f83e
Create Date: 2026-09-27 09:27:29.283021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '767f6d868058'
down_revision: Union[str, Sequence[str], None] = 'aab41d29f83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('position', sa.Numeric(), nullable=True))

    op.execute("""
        UPDATE items
        SET position = sub.rn * 100
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY owner_id, parent_id
                ORDER BY created_at, id
            ) AS rn
            FROM items
        ) AS sub
        WHERE items.id = sub.id
    """)

    op.alter_column('items', 'position', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'position')
    # ### end Alembic commands ###
