"""rename text to title, add description

Revision ID: 806391e9a77b
Revises: e183f1c4c3a4
Create Date: 2026-08-20 09:51:36.129980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '806391e9a77b'
down_revision: Union[str, Sequence[str], None] = 'e183f1c4c3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'text', new_column_name='title')
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'title', new_column_name='text')
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
