"""add projects table and item project_id fk

Revision ID: aab41d29f83e
Revises: 25ada616d58e
Create Date: 2026-09-21 07:52:30.689678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'aab41d29f83e'
down_revision: Union[str, Sequence[str], None] = '25ada616d58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.add_column('items', sa.Column('project_id', sa.Integer(), nullable=True))
    op.alter_column('items', 'owner_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_index(op.f('ix_items_project_id'), 'items', ['project_id'], unique=False)
    op.drop_constraint(op.f('items_owner_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key('items_owner_id_fkey', 'items', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('items_project_id_fkey', 'items', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_project_id_fkey', 'items', type_='foreignkey')
    op.drop_constraint('items_owner_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_owner_id_fkey'), 'items', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_items_project_id'), table_name='items')
    op.alter_column('items', 'owner_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('items', 'project_id')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
